repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
        args:
          - '--maxkb=2048'
          - '--enforce-all'
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
        exclude: ^helm/templates/
      - id: detect-aws-credentials
        args:
          - '--allow-missing-credentials'
      - id: detect-private-key
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-c=./.config/.yamllint.yaml]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        # args: #['--baseline', '.secrets.baseline']
        exclude: externalsecrets-externalsecret.yaml

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: helmlint
      - id: markdown-link-check
        args: [-q]
      - id: yapf
