{{- if gt (int .Values.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "harbor-exempt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harbor-exempt.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "harbor-exempt.selectorLabels" . | nindent 6 }}
{{- end }}
