{{- if .Values.database.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-exempt.fullname" . }}-postgresql-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harbor-exempt.postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.postgresql.credentials.password | quote }}
{{- end }}
