apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-exempt.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harbor-exempt.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-username: {{ .Values.secrets.dbUsername | quote }}
  db-password: {{ .Values.secrets.dbPassword | quote }}
  harbor-password: {{ .Values.secrets.harborPassword | quote }}
